import = ["/home/pedro/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "screen-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
